#!/usr/bin/env python

from modularitea import module
from optparse import OptionParser
import apt_pkg

parser = OptionParser()
parser.add_option("-m", "--module", dest="module")

(option, args) = parser.parse_args()
if not option.module:
    parser.print_help()
    exit(-1)

try:
    module_name = option.module
    module_object = module.Module(module_name)

    total_size = module_object.get_download_size()
    print("Diperlukan download sebesar", apt_pkg.size_to_str(total_size) + "B (perkiraan)")
    print("** Download dapat dilanjutkan lain waktu **")
    user_input = input("Ingin melanjutkan? [Y/n]: ")
    if user_input == "y" or user_input == "Y" or user_input == "":

        module_object.download_archive()
        module_object.add_ppas()
        module_object.download_apt()
        module_object.install_apt()
        module_object.install_archives()
except KeyboardInterrupt:
    exit(-1)